# Simple script to visualize an EDF file

import numpy as np
import matplotlib.pyplot as plt
import lib.EdfFile as EF
import sys

A = np.load('/u/data/alcer/DFXRM_rec/Rec_test/dataarray.npy')

int = np.empty([A.shape[0], A.shape[1]])
Img_array = np.empty([A.shape[0], A.shape[1], A.shape[3], A.shape[4]])
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        int[i,j] = sum(sum(A[i,j,0,:,:]))
        if int[i,j] > 0:
            Img_array[i,j,:,:] = A[i,j,0,:,:]

print Img_array.shape

# Reshape Img_array in a 7x7 array (remove empty combinations)
Array_ang_val = np.empty([A.shape[0], A.shape[1], A.shape[3], A.shape[4]])
Sum_img = np.empty([A.shape[3], A.shape[4]])
for i in range(A.shape[0]):
    num_pos = 0
    for j in range(A.shape[1]):
        int[i,j] = sum(sum(A[i,j,0,:,:]))
        if int[i,j] > 0:
            num_pos = num_pos + 1
            print i,j
            Array_ang_val[i, j,:,:] = A[i,j,0,:,:]
            Sum_img[:,:] = Sum_img[:,:] + Array_ang_val[i, j,:,:]

# Plot the distribution of integrated intensity values in the gamma, theta plane
plt.imshow(int)
plt.title('Distribution of the recorded images as a function of the motor angles')
plt.xlabel('Theta')
plt.ylabel('Gamma')
plt.show()

# Plot the sum of the background images
fig1 = plt.figure()
plt.imshow(Sum_img)
plt.title('Sum of the images collected at omega = 0')
plt.show()

# Plot the various recorded images
fig = plt.figure()
plt.title('Images recorded for at omega = 0')

a1 = fig.add_subplot(5,7,1)
plt.setp(a1.get_xticklabels(), visible=False)
plt.setp(a1.get_yticklabels(), visible=False)
plt.title('(0,1)')
plt.imshow(A[0,1,0,:,:])
a2 = fig.add_subplot(5,7,2)
plt.setp(a2.get_xticklabels(), visible=False)
plt.setp(a2.get_yticklabels(), visible=False)
plt.title('(0,14)')
plt.imshow(A[0,14,0,:,:])
a3 = fig.add_subplot(5,7,3)
plt.setp(a3.get_xticklabels(), visible=False)
plt.setp(a3.get_yticklabels(), visible=False)
plt.title('(0,32)')
plt.imshow(A[0,32,0,:,:])
a4 = fig.add_subplot(5,7,4)
plt.setp(a4.get_xticklabels(), visible=False)
plt.setp(a4.get_yticklabels(), visible=False)
plt.title('(0,41)')
plt.imshow(A[0,41,0,:,:])
a5 = fig.add_subplot(5,7,5)
plt.setp(a5.get_xticklabels(), visible=False)
plt.setp(a5.get_yticklabels(), visible=False)
plt.title('(0,59)')
plt.imshow(A[0,59,0,:,:])
a6 = fig.add_subplot(5,7,6)
plt.setp(a6.get_xticklabels(), visible=False)
plt.setp(a6.get_yticklabels(), visible=False)
plt.title('(0,79)')
plt.imshow(A[0,79,0,:,:])
a7 = fig.add_subplot(5,7,7)
plt.setp(a7.get_xticklabels(), visible=False)
plt.setp(a7.get_yticklabels(), visible=False)
plt.title('(0,91)')
plt.imshow(A[0,91,0,:,:])

b1 = fig.add_subplot(5,7,8)
plt.setp(b1.get_xticklabels(), visible=False)
plt.setp(b1.get_yticklabels(), visible=False)
plt.title('(1,2)')
plt.imshow(A[1,2,0,:,:])
b2 = fig.add_subplot(5,7,9)
plt.setp(b2.get_xticklabels(), visible=False)
plt.setp(b2.get_yticklabels(), visible=False)
plt.title('(1,14)')
plt.imshow(A[1,14,0,:,:])
b3 = fig.add_subplot(5,7,10)
plt.setp(b3.get_xticklabels(), visible=False)
plt.setp(b3.get_yticklabels(), visible=False)
plt.title('(1,32)')
plt.imshow(A[1,32,0,:,:])
b4 = fig.add_subplot(5,7,11)
plt.setp(b4.get_xticklabels(), visible=False)
plt.setp(b4.get_yticklabels(), visible=False)
plt.title('(1,41)')
plt.imshow(A[1,41,0,:,:])
b5 = fig.add_subplot(5,7,12)
plt.setp(b5.get_xticklabels(), visible=False)
plt.setp(b5.get_yticklabels(), visible=False)
plt.title('(1,59)')
plt.imshow(A[1,59,0,:,:])
b6 = fig.add_subplot(5,7,13)
plt.setp(b6.get_xticklabels(), visible=False)
plt.setp(b6.get_yticklabels(), visible=False)
plt.title('(1,74)')
plt.imshow(A[1,74,0,:,:])
b7 = fig.add_subplot(5,7,14)
plt.setp(b7.get_xticklabels(), visible=False)
plt.setp(b7.get_yticklabels(), visible=False)
plt.title('(1,90)')
plt.imshow(A[1,90,0,:,:])

c1 = fig.add_subplot(5,7,15)
plt.setp(c1.get_xticklabels(), visible=False)
plt.setp(c1.get_yticklabels(), visible=False)
plt.title('(3,2)')
plt.imshow(A[3,2,0,:,:])
c2 = fig.add_subplot(5,7,16)
plt.setp(c2.get_xticklabels(), visible=False)
plt.setp(c2.get_yticklabels(), visible=False)
plt.title('(3,14)')
plt.imshow(A[3,14,0,:,:])
c3 = fig.add_subplot(5,7,17)
plt.setp(c3.get_xticklabels(), visible=False)
plt.setp(c3.get_yticklabels(), visible=False)
plt.title('(3,32)')
plt.imshow(A[3,32,0,:,:])
c4 = fig.add_subplot(5,7,18)
plt.setp(c4.get_xticklabels(), visible=False)
plt.setp(c4.get_yticklabels(), visible=False)
plt.title('(3,40)')
plt.imshow(A[3,40,0,:,:])
c5 = fig.add_subplot(5,7,19)
plt.setp(c5.get_xticklabels(), visible=False)
plt.setp(c5.get_yticklabels(), visible=False)
plt.title('(3,59)')
plt.imshow(A[3,59,0,:,:])
c6 = fig.add_subplot(5,7,20)
plt.setp(c6.get_xticklabels(), visible=False)
plt.setp(c6.get_yticklabels(), visible=False)
plt.title('(3,74)')
plt.imshow(A[3,74,0,:,:])
c7 = fig.add_subplot(5,7,21)
plt.setp(c7.get_xticklabels(), visible=False)
plt.setp(c7.get_yticklabels(), visible=False)
plt.title('(3,91)')
plt.imshow(A[3,91,0,:,:])

d1 = fig.add_subplot(5,7,22)
plt.setp(d1.get_xticklabels(), visible=False)
plt.setp(d1.get_yticklabels(), visible=False)
plt.title('(4,2)')
plt.imshow(A[4,2,0,:,:])
d2 = fig.add_subplot(5,7,23)
plt.setp(d2.get_xticklabels(), visible=False)
plt.setp(d2.get_yticklabels(), visible=False)
plt.title('(4,14)')
plt.imshow(A[4,14,0,:,:])
d3 = fig.add_subplot(5,7,24)
plt.setp(d3.get_xticklabels(), visible=False)
plt.setp(d3.get_yticklabels(), visible=False)
plt.title('(4,32)')
plt.imshow(A[4,32,0,:,:])
d4 = fig.add_subplot(5,7,25)
plt.setp(d4.get_xticklabels(), visible=False)
plt.setp(d4.get_yticklabels(), visible=False)
plt.title('(4,41)')
plt.imshow(A[4,41,0,:,:])
d5 = fig.add_subplot(5,7,26)
plt.setp(d5.get_xticklabels(), visible=False)
plt.setp(d5.get_yticklabels(), visible=False)
plt.title('(4,59)')
plt.imshow(A[4,59,0,:,:])
d6 = fig.add_subplot(5,7,27)
plt.setp(d6.get_xticklabels(), visible=False)
plt.setp(d6.get_yticklabels(), visible=False)
plt.title('(4,79)')
plt.imshow(A[4,79,0,:,:])
d7 = fig.add_subplot(5,7,28)
plt.setp(d7.get_xticklabels(), visible=False)
plt.setp(d7.get_yticklabels(), visible=False)
plt.title('(4,91)')
plt.imshow(A[4,91,0,:,:])

e1 = fig.add_subplot(5,7,29)
plt.setp(e1.get_xticklabels(), visible=False)
plt.setp(e1.get_yticklabels(), visible=False)
plt.title('(5,1)')
plt.imshow(A[5,1,0,:,:])
e2 = fig.add_subplot(5,7,30)
plt.setp(e2.get_xticklabels(), visible=False)
plt.setp(e2.get_yticklabels(), visible=False)
plt.title('(5,14)')
plt.imshow(A[5,14,0,:,:])
e3 = fig.add_subplot(5,7,31)
plt.setp(e3.get_xticklabels(), visible=False)
plt.setp(e3.get_yticklabels(), visible=False)
plt.title('(5,32)')
plt.imshow(A[5,32,0,:,:])
e4 = fig.add_subplot(5,7,32)
plt.setp(e4.get_xticklabels(), visible=False)
plt.setp(e4.get_yticklabels(), visible=False)
plt.title('(5,41)')
plt.imshow(A[5,41,0,:,:])
e5 = fig.add_subplot(5,7,33)
plt.setp(e5.get_xticklabels(), visible=False)
plt.setp(e5.get_yticklabels(), visible=False)
plt.title('(5,59)')
plt.imshow(A[5,59,0,:,:])
e6 = fig.add_subplot(5,7,34)
plt.setp(e6.get_xticklabels(), visible=False)
plt.setp(e6.get_yticklabels(), visible=False)
plt.title('(5,74)')
plt.imshow(A[5,74,0,:,:])
e7 = fig.add_subplot(5,7,35)
plt.setp(e7.get_xticklabels(), visible=False)
plt.setp(e7.get_yticklabels(), visible=False)
plt.title('(5,90)')
plt.imshow(A[5,90,0,:,:])

plt.show()
