# Script to analyze the images collected at a certain omega

import numpy as np
import matplotlib.pyplot as plt
import lib.EdfFile as EF
import sys

A = np.load('/u/data/alcer/DFXRM_rec/Rec_test/dataarray.npy')

# Select projection number
omega = 2

int = np.empty([A.shape[0], A.shape[1]])
Img_array = np.empty([A.shape[0], A.shape[1], A.shape[3], A.shape[4]])
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        int[i,j] = sum(sum(A[i,j,omega,:,:]))
	print i, j, int[i,j]
        if int[i,j] > 0:
            Img_array[i,j,:,:] = A[i,j,omega,:,:]

# Analyze distribution of recorded images as a function of angles
int = np.empty([A.shape[0], A.shape[1]])
for oo in range(A.shape[2]):
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            int[i,j] = int[i,j] + sum(sum(A[i,j,oo,:,:]))

plt.imshow(int)
plt.title('Distribution of the recorded images as a function of the motor angles')
plt.xlabel('Theta')
plt.ylabel('Gamma')
plt.show()

# Sum images collected at a certain angle
Array_ang_val = np.empty([A.shape[0], A.shape[1], A.shape[3], A.shape[4]])
Sum_img = np.zeros([A.shape[3], A.shape[4]])
int = np.empty([A.shape[0], A.shape[1]])
for ii in range(A.shape[0]):
    for jj in range(A.shape[1]):
        int[ii,jj] = sum(sum(A[ii,jj,omega,:,:]))
        if int[ii,jj] > 0:
            Array_ang_val[ii, jj,:,:] = A[ii,jj,omega,:,:]
            Sum_img[:,:] = Sum_img[:,:] + A[ii,jj,omega,:,:]
           
# Plot the distribution of integrated intensity values in the gamma, theta plane
plt.imshow(int)
plt.title('Distribution of the recorded images as a function of the motor angles')
plt.xlabel('Theta')
plt.ylabel('Gamma')
plt.show()

# Plot the sum of the background images
fig = plt.figure()
plt.imshow(Sum_img)
plt.xlabel('X (pixels)')
plt.ylabel('Y (pixels)')
plt.show()

sys.exit()

# Plot the various recorded images
fig, axes = plt.subplots(5, 6)

#a1 = fig.add_subplot(7,7,1)
#plt.setp(a1.get_xticklabels(), visible=False)
#plt.setp(a1.get_yticklabels(), visible=False)
#plt.imshow(A[0,2,omega,:,:])
#a2 = fig.add_subplot(7,7,2)
#plt.setp(a2.get_xticklabels(), visible=False)
#plt.setp(a2.get_yticklabels(), visible=False)
#plt.imshow(A[0,14,omega,:,:])
#a3 = fig.add_subplot(7,7,3)
#plt.setp(a3.get_xticklabels(), visible=False)
#plt.setp(a3.get_yticklabels(), visible=False)
#plt.imshow(A[0,32,omega,:,:])
#a4 = fig.add_subplot(7,7,4)
#plt.setp(a4.get_xticklabels(), visible=False)
#plt.setp(a4.get_yticklabels(), visible=False)
#plt.imshow(A[0,41,omega,:,:])
#a5 = fig.add_subplot(7,7,5)
#plt.setp(a5.get_xticklabels(), visible=False)
#plt.setp(a5.get_yticklabels(), visible=False)
#plt.imshow(A[0,59,omega,:,:])
#a6 = fig.add_subplot(7,7,6)
#plt.setp(a6.get_xticklabels(), visible=False)
#plt.setp(a6.get_yticklabels(), visible=False)
#plt.imshow(A[0,74,omega,:,:])
#a7 = fig.add_subplot(7,7,7)
#plt.setp(a7.get_xticklabels(), visible=False)
#plt.setp(a7.get_yticklabels(), visible=False)
#plt.imshow(A[0,91,omega,:,:])

#b1 = fig.add_subplot(7,7,8)
#plt.setp(b1.get_xticklabels(), visible=False)
#plt.setp(b1.get_yticklabels(), visible=False)
#plt.imshow(A[1,2,omega,:,:])
#b2 = fig.add_subplot(7,7,9)
#plt.setp(b2.get_xticklabels(), visible=False)
#plt.setp(b2.get_yticklabels(), visible=False)
#plt.imshow(A[1,14,omega,:,:])
#b3 = fig.add_subplot(7,7,10)
#plt.setp(b3.get_xticklabels(), visible=False)
#plt.setp(b3.get_yticklabels(), visible=False)
#plt.imshow(A[1,32,omega,:,:])
#b4 = fig.add_subplot(7,7,11)
#plt.setp(b4.get_xticklabels(), visible=False)
#plt.setp(b4.get_yticklabels(), visible=False)
#plt.imshow(A[1,41,omega,:,:])
#b5 = fig.add_subplot(7,7,12)
#plt.setp(b5.get_xticklabels(), visible=False)
#plt.setp(b5.get_yticklabels(), visible=False)
#plt.imshow(A[1,59,omega,:,:])
#b6 = fig.add_subplot(7,7,13)
#plt.setp(b6.get_xticklabels(), visible=False)
#plt.setp(b6.get_yticklabels(), visible=False)
#plt.imshow(A[1,74,omega,:,:])
#b7 = fig.add_subplot(7,7,14)
#plt.setp(b7.get_xticklabels(), visible=False)
#plt.setp(b7.get_yticklabels(), visible=False)
#plt.imshow(A[1,91,omega,:,:])

#c1 = fig.add_subplot(7,7,15)
#plt.setp(c1.get_xticklabels(), visible=False)
#plt.setp(c1.get_yticklabels(), visible=False)
#plt.imshow(A[2,2,omega,:,:])
c2 = fig.add_subplot(5,6,1)
plt.setp(c2.get_xticklabels(), visible=False)
plt.setp(c2.get_yticklabels(), visible=False)
plt.imshow(A[2,14,omega,:,:])
c3 = fig.add_subplot(5,6,2)
plt.setp(c3.get_xticklabels(), visible=False)
plt.setp(c3.get_yticklabels(), visible=False)
plt.imshow(A[2,32,omega,:,:])
c4 = fig.add_subplot(5,6,3)
plt.setp(c4.get_xticklabels(), visible=False)
plt.setp(c4.get_yticklabels(), visible=False)
plt.imshow(A[2,41,omega,:,:])
c5 = fig.add_subplot(5,6,4)
plt.setp(c5.get_xticklabels(), visible=False)
plt.setp(c5.get_yticklabels(), visible=False)
plt.imshow(A[2,59,omega,:,:])
c6 = fig.add_subplot(5,6,5)
plt.setp(c6.get_xticklabels(), visible=False)
plt.setp(c6.get_yticklabels(), visible=False)
plt.imshow(A[2,74,omega,:,:])
c7 = fig.add_subplot(5,6,6)
plt.setp(c7.get_xticklabels(), visible=False)
plt.setp(c7.get_yticklabels(), visible=False)
plt.imshow(A[2,91,omega,:,:])

#cc1 = fig.add_subplot(5,6,7)
#plt.setp(cc1.get_xticklabels(), visible=False)
#plt.setp(cc1.get_yticklabels(), visible=False)
#plt.imshow(A[3,2,omega,:,:])
cc2 = fig.add_subplot(5,6,7)
plt.setp(cc2.get_xticklabels(), visible=False)
plt.setp(cc2.get_yticklabels(), visible=False)
plt.imshow(A[3,14,omega,:,:])
cc3 = fig.add_subplot(5,6,8)
plt.setp(cc3.get_xticklabels(), visible=False)
plt.setp(cc3.get_yticklabels(), visible=False)
plt.imshow(A[3,32,omega,:,:])
cc4 = fig.add_subplot(5,6,9)
plt.setp(cc4.get_xticklabels(), visible=False)
plt.setp(cc4.get_yticklabels(), visible=False)
plt.imshow(A[3,41,omega,:,:])
cc5 = fig.add_subplot(5,6,10)
plt.setp(cc5.get_xticklabels(), visible=False)
plt.setp(cc5.get_yticklabels(), visible=False)
plt.imshow(A[3,59,omega,:,:])
cc6 = fig.add_subplot(5,6,11)
plt.setp(cc6.get_xticklabels(), visible=False)
plt.setp(cc6.get_yticklabels(), visible=False)
plt.imshow(A[3,74,omega,:,:])
cc7 = fig.add_subplot(5,6,12)
plt.setp(cc7.get_xticklabels(), visible=False)
plt.setp(cc7.get_yticklabels(), visible=False)
plt.imshow(A[3,91,omega,:,:])

#d1 = fig.add_subplot(7,7,29)
#plt.setp(d1.get_xticklabels(), visible=False)
#plt.setp(d1.get_yticklabels(), visible=False)
#plt.imshow(A[4,2,omega,:,:])
d2 = fig.add_subplot(5,6,13)
plt.setp(d2.get_xticklabels(), visible=False)
plt.setp(d2.get_yticklabels(), visible=False)
plt.imshow(A[4,14,omega,:,:])
d3 = fig.add_subplot(5,6,14)
plt.setp(d3.get_xticklabels(), visible=False)
plt.setp(d3.get_yticklabels(), visible=False)
plt.imshow(A[4,32,omega,:,:])
d4 = fig.add_subplot(5,6,15)
plt.setp(d4.get_xticklabels(), visible=False)
plt.setp(d4.get_yticklabels(), visible=False)
plt.imshow(A[4,41,omega,:,:])
d5 = fig.add_subplot(5,6,16)
plt.setp(d5.get_xticklabels(), visible=False)
plt.setp(d5.get_yticklabels(), visible=False)
plt.imshow(A[4,59,omega,:,:])
d6 = fig.add_subplot(5,6,17)
plt.setp(d6.get_xticklabels(), visible=False)
plt.setp(d6.get_yticklabels(), visible=False)
plt.imshow(A[4,74,omega,:,:])
d7 = fig.add_subplot(5,6,18)
plt.setp(d7.get_xticklabels(), visible=False)
plt.setp(d7.get_yticklabels(), visible=False)
plt.imshow(A[4,91,omega,:,:])

#e1 = fig.add_subplot(7,7,36)
#plt.setp(e1.get_xticklabels(), visible=False)
#plt.setp(e1.get_yticklabels(), visible=False)
#plt.imshow(A[5,2,omega,:,:])
e2 = fig.add_subplot(5,6,19)
plt.setp(e2.get_xticklabels(), visible=False)
plt.setp(e2.get_yticklabels(), visible=False)
plt.imshow(A[5,14,omega,:,:])
e3 = fig.add_subplot(5,6,20)
plt.setp(e3.get_xticklabels(), visible=False)
plt.setp(e3.get_yticklabels(), visible=False)
plt.imshow(A[5,32,omega,:,:])
e4 = fig.add_subplot(5,6,21)
plt.setp(e4.get_xticklabels(), visible=False)
plt.setp(e4.get_yticklabels(), visible=False)
plt.imshow(A[5,41,omega,:,:])
e5 = fig.add_subplot(5,6,22)
plt.setp(e5.get_xticklabels(), visible=False)
plt.setp(e5.get_yticklabels(), visible=False)
plt.imshow(A[5,59,omega,:,:])
e6 = fig.add_subplot(5,6,23)
plt.setp(e6.get_xticklabels(), visible=False)
plt.setp(e6.get_yticklabels(), visible=False)
plt.imshow(A[5,74,omega,:,:])
e7 = fig.add_subplot(5,6,24)
plt.setp(e7.get_xticklabels(), visible=False)
plt.setp(e7.get_yticklabels(), visible=False)
plt.imshow(A[5,91,omega,:,:])

#f1 = fig.add_subplot(7,7,43)
#plt.setp(f1.get_xticklabels(), visible=False)
#plt.setp(f1.get_yticklabels(), visible=False)
#plt.imshow(A[6,2,omega,:,:])
f2 = fig.add_subplot(5,6,25)
plt.setp(f2.get_xticklabels(), visible=False)
plt.setp(f2.get_yticklabels(), visible=False)
plt.imshow(A[6,14,omega,:,:])
f3 = fig.add_subplot(5,6,26)
plt.setp(f3.get_xticklabels(), visible=False)
plt.setp(f3.get_yticklabels(), visible=False)
plt.imshow(A[6,32,omega,:,:])
f4 = fig.add_subplot(5,6,27)
plt.setp(f4.get_xticklabels(), visible=False)
plt.setp(f4.get_yticklabels(), visible=False)
plt.imshow(A[6,41,omega,:,:])
f5 = fig.add_subplot(5,6,28)
plt.setp(f5.get_xticklabels(), visible=False)
plt.setp(f5.get_yticklabels(), visible=False)
plt.imshow(A[6,59,omega,:,:])
f6 = fig.add_subplot(5,6,29)
plt.setp(f6.get_xticklabels(), visible=False)
plt.setp(f6.get_yticklabels(), visible=False)
plt.imshow(A[6,74,omega,:,:])
f7 = fig.add_subplot(5,6,30)
plt.setp(f7.get_xticklabels(), visible=False)
plt.setp(f7.get_yticklabels(), visible=False)
plt.imshow(A[6,91,omega,:,:])

plt.axis('off')
plt.subplots_adjust(wspace=0, hspace=0)

#fig.savefig('test.png')

plt.show()
