close all; clear;
addpath('npy-matlab-master');

% Read 3D npy file, generated by recon3d.py
A = readNPY('grain_ang.npy');

Mean_z = zeros(size(A,3), 1);
for a = 1:size(A,3)
    Mean_z(a) = mean(mean(A(:, :, a, 3)));
end
max_mean = max(Mean_z);

A_final = zeros(size(A));
for i = 1:size(A,3)
    disp(sprintf('Analyzing level %03i', i));
    [Layer_1] = Blobs_finder(A, max_mean, i);
    A_final(:,:,i) = Layer_1(:,:);
end

output = sprintf('Reconstruction.vtk');
savevtk(A_final, output);
